//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hyushik_TournMan_Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hyushik_TournMan_Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking Entry for &quot;{0}&quot; has been deleted.
        /// </summary>
        public static string BreakingEntryDeletedMessage {
            get {
                return ResourceManager.GetString("BreakingEntryDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking score entered for &quot;{0}&quot;.
        /// </summary>
        public static string BreakingJudgeScoreEnteredMessage {
            get {
                return ResourceManager.GetString("BreakingJudgeScoreEnteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking Result recorded for &quot;{0}&quot;.
        /// </summary>
        public static string BreakingResultCreatedMessage {
            get {
                return ResourceManager.GetString("BreakingResultCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one technique.
        /// </summary>
        public static string BreakingTechniqueNotEnteredMessage {
            get {
                return ResourceManager.GetString("BreakingTechniqueNotEnteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was loaded sucessfully!.
        /// </summary>
        public static string CsvFileReadSuccessfullyMessage {
            get {
                return ResourceManager.GetString("CsvFileReadSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input for Yes/No string in file: {0}.
        /// </summary>
        public static string CsvParseYesNoErrorMessage {
            get {
                return ResourceManager.GetString("CsvParseYesNoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was empty or could not be read..
        /// </summary>
        public static string FileUnreadableMessage {
            get {
                return ResourceManager.GetString("FileUnreadableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form attempt for &quot;{0}&quot; has been deleted..
        /// </summary>
        public static string FormDeletedMessage {
            get {
                return ResourceManager.GetString("FormDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form scoring has started for &quot;{0}&quot;.
        /// </summary>
        public static string FormScoreAddedMessage {
            get {
                return ResourceManager.GetString("FormScoreAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form for &quot;{0}&quot; has been scored &quot;{1}&quot;.
        /// </summary>
        public static string FormScoreJudgedMessage {
            get {
                return ResourceManager.GetString("FormScoreJudgedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in.
        /// </summary>
        public static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out.
        /// </summary>
        public static string LogoutSucessfulMessage {
            get {
                return ResourceManager.GetString("LogoutSucessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament &quot;{0}&quot; was successfully created..
        /// </summary>
        public static string NewTournamentCreatedMessage {
            get {
                return ResourceManager.GetString("NewTournamentCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; was checked into ring &quot;{1}&quot;.
        /// </summary>
        public static string ParticipantCheckedInToRingMessage {
            get {
                return ResourceManager.GetString("ParticipantCheckedInToRingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Participant.
        /// </summary>
        public static string ParticipantNotSelectedMessage {
            get {
                return ResourceManager.GetString("ParticipantNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants In Rings Have Been Updated.
        /// </summary>
        public static string ParticipantsInRingsHaveBeenUpdatedMessage {
            get {
                return ResourceManager.GetString("ParticipantsInRingsHaveBeenUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible board depths have been updated.
        /// </summary>
        public static string PossibleBoardDepthsUpdatedMessage {
            get {
                return ResourceManager.GetString("PossibleBoardDepthsUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible board widths have been updated.
        /// </summary>
        public static string PossibleBoardWidthsUpdatedMessage {
            get {
                return ResourceManager.GetString("PossibleBoardWidthsUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring &quot;{0}&quot; has been created..
        /// </summary>
        public static string RingCreatedMessage {
            get {
                return ResourceManager.GetString("RingCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring &quot;{0}&quot; has been deleted..
        /// </summary>
        public static string RingDeletedMessage {
            get {
                return ResourceManager.GetString("RingDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking Results have been hidden for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetBreakingResultsPrivateMessage {
            get {
                return ResourceManager.GetString("SetBreakingResultsPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking Results have been made public for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetBreakingResultsPublicMessage {
            get {
                return ResourceManager.GetString("SetBreakingResultsPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Results have been hidden for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetFormResultsPrivateMessage {
            get {
                return ResourceManager.GetString("SetFormResultsPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Results have been made public for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetFormResultsPublicMessage {
            get {
                return ResourceManager.GetString("SetFormResultsPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparring Results have been hidden for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetSparringResultsPrivateMessage {
            get {
                return ResourceManager.GetString("SetSparringResultsPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparring Results have been made public for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetSparringResultsPublicMessage {
            get {
                return ResourceManager.GetString("SetSparringResultsPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Results have been hidden for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetWeaponResultsPrivateMessage {
            get {
                return ResourceManager.GetString("SetWeaponResultsPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Results have been made public for ring &quot;{0}&quot;.
        /// </summary>
        public static string SetWeaponResultsPublicMessage {
            get {
                return ResourceManager.GetString("SetWeaponResultsPublicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparring result for &quot;{0} vs {1}&quot; in Round {2} has been deleted..
        /// </summary>
        public static string SparringDeletedMessage {
            get {
                return ResourceManager.GetString("SparringDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparring result for &quot;{0} vs {1}&quot; in Round {2} has been created.
        /// </summary>
        public static string SparringResultCreatedMessage {
            get {
                return ResourceManager.GetString("SparringResultCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique &quot;{0}&quot; was added.
        /// </summary>
        public static string TechniqueAddedMessage {
            get {
                return ResourceManager.GetString("TechniqueAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique &quot;{0}&quot; has been deleted.
        /// </summary>
        public static string TechniqueDeletedMessage {
            get {
                return ResourceManager.GetString("TechniqueDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technique &quot;{0}&quot; was updated.
        /// </summary>
        public static string TechniqueUpdatedMessage {
            get {
                return ResourceManager.GetString("TechniqueUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament &quot;{0}&quot; has been activated.
        /// </summary>
        public static string TournamentActivatedMessage {
            get {
                return ResourceManager.GetString("TournamentActivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tournament &quot;{0}&quot; has been deactivated.
        /// </summary>
        public static string TournamentDeactivatedMessage {
            get {
                return ResourceManager.GetString("TournamentDeactivatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tournament must have a name..
        /// </summary>
        public static string TournamentMustHaveNameMessage {
            get {
                return ResourceManager.GetString("TournamentMustHaveNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament name &quot;{0}&quot; is already in use..
        /// </summary>
        public static string TournamentNameInUseMessage {
            get {
                return ResourceManager.GetString("TournamentNameInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested tournament could not be found.
        /// </summary>
        public static string TournamentNotFoundMessage {
            get {
                return ResourceManager.GetString("TournamentNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &quot;{1}&quot; has been given to user &quot;{0}&quot;.
        /// </summary>
        public static string UserAddedRoleMessage {
            get {
                return ResourceManager.GetString("UserAddedRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; already has role &quot;{1}&quot;.
        /// </summary>
        public static string UserAlreadyHasRoleMessage {
            get {
                return ResourceManager.GetString("UserAlreadyHasRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; does not have role &quot;{1}&quot;.
        /// </summary>
        public static string UserDoesNotAlreadyHaveRoleMessage {
            get {
                return ResourceManager.GetString("UserDoesNotAlreadyHaveRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &quot;{1}&quot; has been revoked from user &quot;{0}&quot;.
        /// </summary>
        public static string UserRemovedRoleMessage {
            get {
                return ResourceManager.GetString("UserRemovedRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon attempt for &quot;{0}&quot; has been deleted..
        /// </summary>
        public static string WeaponDeletedMessage {
            get {
                return ResourceManager.GetString("WeaponDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon scoring has started for &quot;{0}&quot;.
        /// </summary>
        public static string WeaponScoreAddedMessage {
            get {
                return ResourceManager.GetString("WeaponScoreAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon for &quot;{0}&quot; has been scored &quot;{1}&quot;.
        /// </summary>
        public static string WeaponScoreJudgedMessage {
            get {
                return ResourceManager.GetString("WeaponScoreJudgedMessage", resourceCulture);
            }
        }
    }
}
